name: LanthyrChatnSigns
version: ${project.version}
main: lanthyrchatnsigns.lanthyrchatnsigns.LanthyrChatnSigns
softdepend: [Herochat, Vault]
authors: [Laleem, GreatThane]
description: Editable signs and Chat stuff
website: https://lanthyrrp.enjin.com/home
commands:
  editsign:
    description: some stuff
  chatcolor:
    description: some stuff